# Generated by Django 5.2 on 2025-05-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog_alter_career_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='career',
            name='responsibilities',
            field=models.TextField(),
        ),
    ]
